services:
  openpcdet:
    image: openpcdet-dev-${USER}
    env_file:
      - .env
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: openpcdet-env
        HOST_UID: $HOST_UID
        HOST_GID: $HOST_GID
        HOST_USER: ${USER}        
    container_name: centerpoint
    user: $HOST_UID:$HOST_GID
    volumes:
      - .:/home/${USER}/OpenPCDet
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.ssh:/home/${USER}/.ssh
      - $HOME/.config:/home/${USER}/.config
      - $HOME/.gitconfig:/home/${USER}/.gitconfig
      - ~/Dataset:/Dataset
      - ~/DATA/NAS/nfsRoot:/nfsRoot
    working_dir: /home/${USER}/OpenPCDet
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - TZ="Asia/Seoul"
    privileged: true
    network_mode: host
    stdin_open: true
    tty: true
    ipc: host
    pid: host
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
